### ISSUE TITLE
HTTP authentication from outside the host running the cluster

### ISSUE THREAD

**Issue by AIMENCristianVegaMuniz** [aminenafdou/hadoop-developer-starterkit#3]
Hi!
First of all, thanks for the repo! Kerberos authentication in Hadoop is something not pleasant to investigate as there is few information about it. It really helps to have a repo that launch a full cluster ready to go, honestly.

Currently I'm having a problem trying to authenticate through HTTP requests from a different machine to the Hadoop cluster inside my host, I hope you could help me in any way to undestand the problem.

- In the compose, I exposed the ports for each container to the host, so now I can easily add principals and kinit from any machine outside the host, and get access to Hadoop. Like this (for the namenode):
ports:
   - 9871:9871
 
- Also, i set dfs.web.authentication.kerberos.principal in hdfs-site.xml and hadoop.http.authentication.kerberos.principal and core-site.xml to HTTP/_HOST@HADOOP.LOCAL. When HTTP authentication requests come with the IP of namenode-1.hadoop, this principal is translated to HTTP/namenode-1.hadoop@HADOOP.LOCAL. If they come from the IP of the host, the principal is HTTP/IP-of-host@HADOOP.LOCAL.

- I also set hadoop.http.authentication.kerberos.keytab and dfs.web.authentication.kerberos.keytab with a spnego.service.keytab

- I changed the sh scripts so the namenode create these principals and add them to the same spnego.service.keytab

- I created some HTTP/principals to login. From inside the host, it works when I send the curl request to https://namenode-1.hadoop:9871 i.e. the IP of the Namenode container, but it doesn't work when I use https://ip-of-my-host:9871, either from the host itself or other machine. Using the same user principal in both cases, and doing the kinit successfuly before hand, so probably is a missconfiguration in Hadoop.

Don't know if you had any previous experience using HTTP authentication with Hadoop, or if maybe I'm missing some special configuration, any help is appreciated. Thanks in advance!

**Comment by AIMENCristianVegaMuniz** [comment]
For anyone interested, I ended up creating a principal like this HTTP/IP-of-host@HADOOP.LOCAL using the IP of the host, and configured the namenode to use it in hdfs-site.xml and core-site.xml. This way, HTTP requests from inside the server don't work, but in my case is enough. :)

**Comment by aminenafdou** [comment]
Thank you for your feed back ! and i'm sorry for my late response !
